---
title: "Global study of Gender Inequality in Education Access"
author: "Jorge Bris Moreno, Liz Kovalchuk, Tiana Le, and Sheeba Moghal"
format:
  html:
    embed-resources: true
    toc: true
    before_body: scripts.html
editor_options:
  chunk_output_type: console
execute:
  echo: false
---

# Abstract
In this article we aim to explore gender inequality in education access across the globe. Education is one of the key drivers in the development of society. For that reason, we will be using data obrained from the World Bank to analyze the relationship between this gap and other factors such as GDP, GNI, population, and other variables. The data is utilized is from the years 2010, 2011, 2012, 2013, and 2014. We will focuss on a larger global scale and then dive down into specific regions in order to identify trends and patterns that are important to explore further through our analysis. Additionally, we will be looking at what regions have the highest diparity in education enrollment based on gender and what factors may be contributing to this disparity, whether they are economic, social, or political.


# Introduction
Education is one of the most important factors in the development of society. Throughout all history, women have been marginalized in the educational system. This has led to a significant gap in the education. The United Nations has recognized this issue and has emphasized the importance of education in the sustainable development of society. While this gender gap has been closing over the years, we will aim to explore the current state of this gap and what are the factors that may be contributing to it so that we can better understand how to address this issue. 

To do this, we will not only take into account factors like global development or macroeconomics but we will try to dive deeper into gender roles in society.  We will address six critical questions:

- How do literacy rates correlate with population growth rates across different regions and time periods?
- How does the allocation of resources to education influence literacy rates?
-  In what ways do literacy and education contribute to economic growth and development?
- To what extent does gender equality manifest in educational access, participation, and outcomes?
- How do trends in education mirror trends in employment, particularly regarding gender?
- What specific obstacles hinder gender equality in educational access, retention, and achievement? 

By answering the above, we will be able to find out the importance of education in the development of countries and population, the influence it has within the working industry, what role economics plays in education, and explore further issues in the current gender gap. Hopefully, this study will help us better understand this gap and how to address it in the future.


# Female Gross Enrollment Ratios by Region (2014)

To begin our analysis, we will be looking at different regions usually studied by global organizations like the World Bank. We will be focusing on the following regions: Arab World, East Asia & Pacific, Euro area, Europe & Central Asia, Heavily indebted poor countries (HIPC), Latin America & Caribbean (excluding high income), Middle East & North Africa, Middle East & North Africa (excluding high income), OECD members, and Sub-Saharan Africa (excluding high income). The objective is to visualize the differences in women's enrollment at different education levels across the world at a global scale and identify any trends or patterns that may arise. This will also allow us to consider if some regions are worth exploring in more detail than others in our analysis.
```{r, echo=FALSE, results='asis', runtime="js"}
cat('
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
')
```

```{ojs, message=FALSE, warning=FALSE, echo = FALSE, return = FALSE}
// Define the initial dataset
initialData = [
  {"Country Name":"Arab World","Indicator":"lower secondary","Value":81.054},
  {"Country Name":"Arab World","Indicator":"post-secondary non-tertiary","Value":"NA"},
  {"Country Name":"Arab World","Indicator":"pre-primary","Value":25.3707},
  {"Country Name":"Arab World","Indicator":"primary","Value":93.608},
  {"Country Name":"Arab World","Indicator":"secondary","Value":67.9689},
  {"Country Name":"Arab World","Indicator":"tertiary","Value":28.768},
  {"Country Name":"Arab World","Indicator":"upper secondary","Value":54.5065},
  {"Country Name":"East Asia & Pacific","Indicator":"lower secondary","Value":96.6641},
  {"Country Name":"East Asia & Pacific","Indicator":"post-secondary non-tertiary","Value":"NA"},
  {"Country Name":"East Asia & Pacific","Indicator":"pre-primary","Value":76.0034},
  {"Country Name":"East Asia & Pacific","Indicator":"primary","Value":104.9668},
  {"Country Name":"East Asia & Pacific","Indicator":"secondary","Value":88.3206},
  {"Country Name":"East Asia & Pacific","Indicator":"tertiary","Value":41.4262},
  {"Country Name":"East Asia & Pacific","Indicator":"upper secondary","Value":79.7367},
  {"Country Name":"Euro area","Indicator":"lower secondary","Value":108.7706},
  {"Country Name":"Euro area","Indicator":"post-secondary non-tertiary","Value":"NA"},
  {"Country Name":"Euro area","Indicator":"pre-primary","Value":102.3132},
  {"Country Name":"Euro area","Indicator":"primary","Value":103.4798},
  {"Country Name":"Euro area","Indicator":"secondary","Value":110.7075},
  {"Country Name":"Euro area","Indicator":"tertiary","Value":76.299},
  {"Country Name":"Euro area","Indicator":"upper secondary","Value":112.9169},
  {"Country Name":"Europe & Central Asia","Indicator":"lower secondary","Value":103.7713},
  {"Country Name":"Europe & Central Asia","Indicator":"post-secondary non-tertiary","Value":"NA"},
  {"Country Name":"Europe & Central Asia","Indicator":"pre-primary","Value":74.2163},
  {"Country Name":"Europe & Central Asia","Indicator":"primary","Value":103.1583},
  {"Country Name":"Europe & Central Asia","Indicator":"secondary","Value":105.389},
  {"Country Name":"Europe & Central Asia","Indicator":"tertiary","Value":69.8713},
  {"Country Name":"Europe & Central Asia","Indicator":"upper secondary","Value":107.4027},
  {"Country Name":"Heavily indebted poor countries (HIPC)","Indicator":"lower secondary","Value":"NA"},
  {"Country Name":"Heavily indebted poor countries (HIPC)","Indicator":"post-secondary non-tertiary","Value":18.0427},
  {"Country Name":"Heavily indebted poor countries (HIPC)","Indicator":"pre-primary","Value":98.0805},
  {"Country Name":"Heavily indebted poor countries (HIPC)","Indicator":"primary","Value":35.621},
  {"Country Name":"Heavily indebted poor countries (HIPC)","Indicator":"secondary","Value":6.233},
  {"Country Name":"Heavily indebted poor countries (HIPC)","Indicator":"tertiary","Value":24.4659},
  {"Country Name":"Heavily indebted poor countries (HIPC)","Indicator":"upper secondary","Value":108.0586},
  {"Country Name":"Latin America & Caribbean (excluding high income)","Indicator":"lower secondary","Value":"NA"},
  {"Country Name":"Latin America & Caribbean(excluding high income)","Indicator":"post-secondary non-tertiary","Value":72.4493},
  {"Country Name":"Latin America & Caribbean (excluding high income)","Indicator":"pre-primary","Value":107.3809},
  {"Country Name":"Latin America & Caribbean (excluding high income)","Indicator":"primary","Value":97.1722},
  {"Country Name":"Latin America & Caribbean (excluding high income)","Indicator":"secondary","Value":48.967},
  {"Country Name":"Latin America & Caribbean (excluding high income)","Indicator":"tertiary","Value":84.4792},
  {"Country Name":"Latin America & Caribbean (excluding high income)","Indicator":"upper secondary","Value":88.4424},
  {"Country Name":"Middle East & North Africa","Indicator":"lower secondary","Value":"NA"},
  {"Country Name":"Middle East & North Africa","Indicator":"post-secondary non-tertiary","Value":29.5462},
  {"Country Name":"Middle East & North Africa","Indicator":"pre-primary","Value":103.047},
  {"Country Name":"Middle East & North Africa","Indicator":"primary","Value":76.9069},
  {"Country Name":"Middle East & North Africa","Indicator":"secondary","Value":38.2514},
  {"Country Name":"Middle East & North Africa","Indicator":"tertiary","Value":65.6759},
  {"Country Name":"Middle East & North Africa","Indicator":"upper secondary","Value":86.992},
  {"Country Name":"Middle East & North Africa (excluding high income)","Indicator":"lower secondary","Value":"NA"},
  {"Country Name":"Middle East & North Africa (excluding high income)","Indicator":"post-secondary non-tertiary","Value":26.8679},
  {"Country Name":"Middle East & North Africa (excluding high income)","Indicator":"pre-primary","Value":102.4904},
  {"Country Name":"Middle East & North Africa (excluding high income)","Indicator":"primary","Value":74.3971},
  {"Country Name":"Middle East & North Africa (excluding high income)","Indicator":"secondary","Value":36.1012},
  {"Country Name":"Middle East & North Africa (excluding high income)","Indicator":"tertiary","Value":62.3747},
  {"Country Name":"Middle East & North Africa (excluding high income)","Indicator":"upper secondary","Value":107.3207},
  {"Country Name":"OECD members","Indicator":"lower secondary","Value":79.3329},
  {"Country Name":"OECD members","Indicator":"post-secondary non-tertiary","Value":"NA"},
  {"Country Name":"OECD members","Indicator":"pre-primary","Value":102.2592},
  {"Country Name":"OECD members","Indicator":"primary","Value":104.3177},
  {"Country Name":"OECD members","Indicator":"secondary","Value":75.5335},
  {"Country Name":"OECD members","Indicator":"tertiary","Value":101.3419},
  {"Country Name":"OECD members","Indicator":"upper secondary","Value":46.1386},
  {"Country Name":"Sub-Saharan Africa (excluding high income)","Indicator":"lower secondary","Value":"NA"},
  {"Country Name":"Sub-Saharan Africa (excluding high income)","Indicator":"post-secondary non-tertiary","Value":22.0271},
  {"Country Name":"Sub-Saharan Africa (excluding high income)","Indicator":"pre-primary","Value":94.7689},
  {"Country Name":"Sub-Saharan Africa (excluding high income)","Indicator":"primary","Value":39.5373},
  {"Country Name":"Sub-Saharan Africa (excluding high income)","Indicator":"secondary","Value":7.2426},
  {"Country Name":"Sub-Saharan Africa (excluding high income)","Indicator":"tertiary","Value":31.7493},
  {"Country Name":"Sub-Saharan Africa (excluding high income)","Indicator":"upper secondary","Value":108.0586}
];

// Filter and parse the dataset to remove "NA" values and convert "Value" to float
parsedData = initialData.filter(d => d.Value !== "NA").map(d => ({
  ...d,
  Value: parseFloat(d.Value)
}));

// Reduce the data to group it by "Country Name" and accumulate the indicators and values
seriesData = parsedData.reduce((acc, { "Country Name": countryName, Indicator, Value }) => {
  let group = acc.find(g => g.name === countryName);
  if (!group) {
    group = { name: countryName, data: [] };
    acc.push(group);
  }
  group.data.push({ name: Indicator, value: Value });
  return acc;
}, []);
```

<figure>
  <div id="container"></div>
  <figcaption>This chart shows the Female Gross Enrollment Ratios by Region for the year 2014. These region delimitations have been chosen from what global organizations like the World Bank utilize for their studies. You can select and deselect regions to focus on different regions, each bubble inside the region represents an education level, and the values inside are the female gross enrollment ration for 2014. The sizes of the bubbles correlate to the values. If levels of education are not present in a region is due to the lack of information about that specific combination of education level and region.</figcaption>
</figure>

```{ojs, message=FALSE, warning=FALSE, echo = FALSE}

function renderChart() {
    Highcharts.chart('container', {
        chart: {
            type: 'packedbubble',
            height: '100%'
        },
        title: {
            text: 'Female Gross Enrollment Ratios by Region (2014)'
        },
        tooltip: {
            useHTML: true,
            pointFormat: '<b>{point.name}:</b> {point.value}%'
        },
        plotOptions: {
            packedbubble: {
                minSize: '10%',
                maxSize: '100%',
                zMin: 0,
                zMax: 400,
                layoutAlgorithm: {
                    gravitationalConstant: 0.05,
                    splitSeries: true,
                    seriesInteraction: false,
                    dragBetweenSeries: true,
                    parentNodeLimit: true
                },
                dataLabels: {
                    enabled: true,
                    format: '{point.name}',
                    style: {
                        color: 'black',
                        textOutline: 'none',
                        fontWeight: 'normal'
                    }
                }
            }
        },
        series: seriesData
    })};
renderChart();
```

From the chart above, not surprisingly, we can see that for all regions, the higher the education level, the lower the enrollment ratio. This is expected as the higher the education level, the more specialized and less accessible it becomes. However, we can see that there are some regions that have higher enrollment ratios than others. While looking at every regions data is important, it is worth noting that for some of them there is a lack of information for some education levels. This limits our ability to make a full comparison between regions. However, it still allows us to see the disparities between regions. Subsahaaran Africa, heavily indebted poor countries, and the Middle East and North Africa seem to have the lowest enrollment ratios across all education levels for female students. On the other hand, the Euro area, Europe and Central Asia, and OECD members have the highest enrollment ratios for female students. 

This is important information to consider as we move forward with our analysis. One can think that it may be due to economic reasons, social and ideological reasons, or even political reasons. However, this problem has been present for decades and instead of taking assumptions to answer this question, we should identify the key reasons for this disparity and address it accordingly.