project:
  type: website

website:
  title: "Global Female Education Attainment"
  navbar:
    left:
      - text: Global Female Education Attainment
        href: index.qmd
      - href: "https://github.com/ek976/data_viz_final_project"
        text: Code  
      - href: Authors.qmd
        text: Authors


format:
  html:
    theme: lux
    toc: true



