project:
  type: website

website:
  title: "DSAN5200"
  navbar:
    left:
      - text: Global Female Education Attainment
        href: index.qmd
      - href: "https://github.com/gu-dsan5200/spring-2024-dsan-5200-project-repo-project-group-20"
        text: Code  
      - href: Authors.qmd
        text: Authors


format:
  html:
    theme: lux
    toc: true



